"""
Unit tests for the code generation + QA layer.
"""
from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from spec_to_test.generators.fixture_gen import FixtureGenerator
from spec_to_test.generators.pytest_gen import PytestGenerator
from spec_to_test.generators.qa import SemanticQA
from spec_to_test.models.spec import SpecDocument
from spec_to_test.models.state import ReusableState, StateCondition
from spec_to_test.models.testcase import (
    Assertion,
    Direction,
    Precondition,
    Step,
    TestCase,
    TestType,
)


# ------------------------------------------------------------------ #
# Fixtures: minimal SpecDocument                                      #
# ------------------------------------------------------------------ #

@pytest.fixture
def minimal_spec_doc() -> SpecDocument:
    return SpecDocument(
        spec_id="ocpp-2.0.1-part6",
        spec_version="2.0.1",
        test_cases=[
            TestCase(
                id="TC_B01",
                title="Boot Notification",
                test_type=TestType.MESSAGE_SEQUENCE,
                source_chunk_id="TC_B01",
                page_start=42,
                page_end=43,
                preconditions=[
                    Precondition(
                        description="CS not connected",
                        reusable_state_ref="RS_001",
                    )
                ],
                steps=[
                    Step(
                        step_number=1,
                        description="CS sends BootNotificationRequest",
                        action="Send BootNotificationRequest",
                        message_type="BootNotification",
                        direction=Direction.CS_TO_CSMS,
                        assertions=[
                            Assertion(
                                description="Response status is Accepted",
                                field_path="response.registration_status",
                                expected_value="RegistrationStatusType.accepted",
                                operator="eq",
                            )
                        ],
                    )
                ],
                expected_outcome="CS is registered.",
            ),
            TestCase(
                id="TC_C01",
                title="Status Notification",
                test_type=TestType.MESSAGE_SEQUENCE,
                source_chunk_id="TC_C01",
                page_start=80,
                page_end=81,
                steps=[
                    Step(
                        step_number=1,
                        description="CS sends StatusNotificationRequest",
                        action="Send StatusNotificationRequest",
                        message_type="StatusNotification",
                        direction=Direction.CS_TO_CSMS,
                        assertions=[],
                    )
                ],
            ),
        ],
        reusable_states=[
            ReusableState(
                id="RS_001",
                title="CSMS Simulated State",
                source_chunk_id="RS_001",
                page_start=15,
                page_end=15,
                conditions=[
                    StateCondition(
                        condition="CSMS running",
                        description="Simulator is started",
                    )
                ],
            )
        ],
    )


# ------------------------------------------------------------------ #
# PytestGenerator                                                     #
# ------------------------------------------------------------------ #

def test_pytest_gen_creates_files(tmp_path, minimal_spec_doc):
    gen = PytestGenerator(output_dir=tmp_path)
    written = gen.generate(minimal_spec_doc)
    assert len(written) > 0
    for path in written:
        assert path.exists()


def test_pytest_gen_files_contain_test_functions(tmp_path, minimal_spec_doc):
    gen = PytestGenerator(output_dir=tmp_path)
    written = gen.generate(minimal_spec_doc)
    all_content = "\n".join(p.read_text() for p in written)
    assert "async def test_" in all_content


def test_pytest_gen_has_auto_generated_header(tmp_path, minimal_spec_doc):
    gen = PytestGenerator(output_dir=tmp_path)
    written = gen.generate(minimal_spec_doc)
    for path in written:
        content = path.read_text()
        assert "AUTO-GENERATED by spec-to-test" in content


def test_pytest_gen_groups_by_category(tmp_path, minimal_spec_doc):
    gen = PytestGenerator(output_dir=tmp_path)
    written = gen.generate(minimal_spec_doc)
    names = {p.name for p in written}
    # TC_B01 → test_tc_b.py, TC_C01 → test_tc_c.py
    assert "test_tc_b.py" in names
    assert "test_tc_c.py" in names


def test_pytest_gen_uses_mobilityhouse_enum(tmp_path, minimal_spec_doc):
    """Generated test code must reference mobilityhouse enum members, not strings."""
    gen = PytestGenerator(output_dir=tmp_path)
    written = gen.generate(minimal_spec_doc)
    b_content = (tmp_path / "test_tc_b.py").read_text()
    assert "RegistrationStatusType" in b_content


def test_pytest_gen_has_pytest_fixture_import(tmp_path, minimal_spec_doc):
    gen = PytestGenerator(output_dir=tmp_path)
    gen.generate(minimal_spec_doc)
    b_content = (tmp_path / "test_tc_b.py").read_text()
    assert "import pytest" in b_content


# ------------------------------------------------------------------ #
# FixtureGenerator                                                    #
# ------------------------------------------------------------------ #

def test_fixture_gen_creates_conftest(tmp_path, minimal_spec_doc):
    gen = FixtureGenerator(output_dir=tmp_path)
    path = gen.generate(minimal_spec_doc)
    assert path.exists()
    assert path.name == "conftest.py"


def test_fixture_gen_has_pytest_fixture_decorator(tmp_path, minimal_spec_doc):
    gen = FixtureGenerator(output_dir=tmp_path)
    path = gen.generate(minimal_spec_doc)
    content = path.read_text()
    assert "@pytest.fixture" in content


def test_fixture_gen_has_auto_generated_header(tmp_path, minimal_spec_doc):
    gen = FixtureGenerator(output_dir=tmp_path)
    path = gen.generate(minimal_spec_doc)
    assert "AUTO-GENERATED by spec-to-test" in path.read_text()


# ------------------------------------------------------------------ #
# SemanticQA                                                          #
# ------------------------------------------------------------------ #

@pytest.fixture
def qa_test_files(tmp_path, minimal_spec_doc) -> list[Path]:
    gen = PytestGenerator(output_dir=tmp_path)
    return gen.generate(minimal_spec_doc)


def test_semantic_qa_high_similarity(tmp_path, qa_test_files):
    """
    When the source chunk markdown is very similar to the docstring,
    similarity should be above threshold and test should NOT be flagged.
    """
    qa = SemanticQA(threshold=0.7)

    # Build chunk_index where TC_B01 has a very similar description
    chunk_index = {
        "TC_B01": (
            "Boot Notification — CS sends BootNotificationRequest. "
            "CSMS responds with BootNotificationResponse status=Accepted. "
            "Test Type: message_sequence"
        ),
        "TC_C01": (
            "Status Notification — CS sends StatusNotificationRequest. "
            "Test Type: message_sequence"
        ),
    }

    results = qa.run(qa_test_files, chunk_index, output_path=None)
    assert len(results) > 0

    high_sim = [r for r in results if r.test_id == "test_tc_b01"]
    if high_sim:
        # High-similarity pair should not be flagged
        assert not high_sim[0].flagged, (
            f"Expected not flagged, got similarity={high_sim[0].similarity}"
        )


def test_semantic_qa_low_similarity_flagged(tmp_path, qa_test_files):
    """
    When source chunk is completely unrelated, test should be flagged.
    """
    qa = SemanticQA(threshold=0.7)

    # Completely unrelated content for chunk
    chunk_index = {
        "TC_B01": "This is about recipes and cooking pasta.",
        "TC_C01": "Weather forecast: sunny with chance of rain.",
    }

    results = qa.run(qa_test_files, chunk_index, output_path=None)
    flagged = [r for r in results if r.flagged]
    assert len(flagged) > 0


def test_semantic_qa_writes_report(tmp_path, qa_test_files):
    qa = SemanticQA(threshold=0.7)
    chunk_index = {"TC_B01": "Boot Notification test", "TC_C01": "Status Notification"}
    report_path = tmp_path / "qa_report.json"

    qa.run(qa_test_files, chunk_index, output_path=report_path)

    assert report_path.exists()
    report = json.loads(report_path.read_text())
    assert "total_tests" in report
    assert "flagged_count" in report
    assert "threshold" in report
    assert report["threshold"] == 0.7
